### ISSUE TITLE
Commas breaking import, escaping them not working

### ISSUE THREAD

**Issue by steven-parker** [BrennenRocks/fishbowl-js#3]
If there are commas in fields, such as ProductDescription - the import breaks everything after the comma. If the comma is escaped by replacing it with \, it doesn't change anything.
Is there a method that should be used? I am now wrapping all fields in double quotes and that is working.

**Comment by BrennenRocks** [comment]
@steven-parker which version of fishbowl-js are you on?

**Comment by tylerhahn** [comment]
I'm also experiencing the bug @steven-parker is describing.
I'm using 2.3.0.

Specifically I have a Address Contact (Company Name, LLC) that when I attempt to import I get

err: 1500 - The following lines of the CSV import do not have the correct format or contain incompatible data. Due to these errors, only some information was imported. Please make the appropriate changes to these lines and re-import the file.

For input string: "LLC"
Line Number: 2

**Comment by steven-parker** [comment]
I ended up just wrapping all the strings, and didn't bother escaping commas. Just a simple `"${field}"` replacement.

**Comment by BrennenRocks** [comment]
Fixed in 2.4.0
